spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_LOCAL}:${DB_PORT_LOCAL}/y2rssdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
server:
  port: ${SERVICE_PORT_LOCAL}
