spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/y2rssdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD
server:
  port: ${SERVICE_PORT}
