spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_PROD}:${DB_PORT_PROD}/y2rssdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
